Added more docker functions

diff --git a/lib/docker b/lib/docker
--- a/lib/docker
+++ b/lib/docker
@@ -1,18 +1,52 @@
 # vim: set ft=sh:
+
+# Shortcut for grepping running containers
+function __docker_list_all() {
+  docker ps -a | tail -n +2
+}
+
+function docker-list() {
+  if [[ -z "$@" ]]; then
+    __docker_list_all
+  else
+    __docker_list_all | grep $@
+  fi;
+}
+
+function docker-grep() {
+  docker-list | grep $@
+}
+
 # Shortcut for killing and removing docker containers
+function __docker_output() {
+  if [[ "$1" == "0" ]]; then
+    local s=$'\xe2\x9c\x93'
+    local c=2
+  else
+    local s=$'\xe2\x9c\x97'
+    local c=1
+  fi
+
+  printf "$(tput bold)$(tput setaf ${c})"$s"$(tput sgr0)\n"
+}
 function docker-rm() {
-  local all_good=0
+  local cool=
   echo "Removing containers..."
-  while read cid; do
-    printf "  $(tput bold)"
-    sudo docker kill $cid 2>&1 > /dev/null
-    if sudo docker rm $cid 2>&1 > /dev/null; then
-      printf "$(tput setaf 2)"$'\xe2\x9c\x93'
-    else
-      all_good=1
-      printf "$(tput setaf 1)"$'\xe2\x9c\x97'
-    fi
-    printf "$(tput sgr0) ${cid}\n"
+
+  while read container; do
+    # Parse the cid
+    local cid="$(printf $container | awk '{print $1}')"
+
+    # Output the container CID
+    printf "  $cid "
+
+    # Kill the container
+    docker kill $cid > /dev/null || exit 1
+
+    # Remove the container, break on error
+    docker rm $cid > /dev/null
+    cool=$?
+    __docker_output $cool
+    [[ "$cool" != "0" ]] && break || true
   done
-  [[ $all_good -eq 0 ]]
 }
